/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/characters/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List characters */
        get: operations["characters_list"];
        put?: never;
        /** @description Create a new character */
        post: operations["characters_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get character details */
        get: operations["characters_retrieve"];
        /** @description Update a character */
        put: operations["characters_update"];
        post?: never;
        /** @description ViewSet for managing characters. */
        delete: operations["characters_destroy"];
        options?: never;
        head?: never;
        /** @description Partially update a character */
        patch: operations["characters_partial_update"];
        trace?: never;
    };
    "/api/characters/{id}/loot/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Loot an item at character's position */
        post: operations["characters_loot_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{id}/move/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Move character to a new position */
        post: operations["characters_move_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List all games */
        get: operations["games_list"];
        put?: never;
        /** @description Create a new game */
        post: operations["games_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get game details */
        get: operations["games_retrieve"];
        /** @description Update a game */
        put: operations["games_update"];
        post?: never;
        /** @description Delete a game */
        delete: operations["games_destroy"];
        options?: never;
        head?: never;
        /** @description Partially update a game */
        patch: operations["games_partial_update"];
        trace?: never;
    };
    "/api/games/{id}/current_state/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get current world state for a game */
        get: operations["games_current_state_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{id}/start/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Start a game */
        post: operations["games_start_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hex-tiles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List hex tiles */
        get: operations["hex_tiles_list"];
        put?: never;
        /** @description Create a hex tile */
        post: operations["hex_tiles_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/hex-tiles/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get hex tile details */
        get: operations["hex_tiles_retrieve"];
        /** @description Update a hex tile */
        put: operations["hex_tiles_update"];
        post?: never;
        /** @description ViewSet for managing hex tiles on the game map. */
        delete: operations["hex_tiles_destroy"];
        options?: never;
        head?: never;
        /** @description Partially update a hex tile */
        patch: operations["hex_tiles_partial_update"];
        trace?: never;
    };
    "/api/hex-tiles/nearby/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get tiles in a radius around a coordinate */
        get: operations["hex_tiles_nearby_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interactables/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List interactable objects */
        get: operations["interactables_list"];
        put?: never;
        /** @description Create an interactable object */
        post: operations["interactables_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interactables/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get interactable details */
        get: operations["interactables_retrieve"];
        /** @description Update an interactable object */
        put: operations["interactables_update"];
        post?: never;
        /** @description ViewSet for managing interactable objects. */
        delete: operations["interactables_destroy"];
        options?: never;
        head?: never;
        /** @description Partially update an interactable object */
        patch: operations["interactables_partial_update"];
        trace?: never;
    };
    "/api/interactables/{id}/interact/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Interact with an object */
        post: operations["interactables_interact_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map-items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List map items */
        get: operations["map_items_list"];
        put?: never;
        /** @description Spawn a map item */
        post: operations["map_items_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map-items/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get map item details */
        get: operations["map_items_retrieve"];
        /** @description Update a map item */
        put: operations["map_items_update"];
        post?: never;
        /** @description ViewSet for managing map items (loot). */
        delete: operations["map_items_destroy"];
        options?: never;
        head?: never;
        /** @description Partially update a map item */
        patch: operations["map_items_partial_update"];
        trace?: never;
    };
    "/api/players/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List players */
        get: operations["players_list"];
        put?: never;
        /** @description Join a game as a player */
        post: operations["players_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/players/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get player details */
        get: operations["players_retrieve"];
        /** @description Update player info */
        put: operations["players_update"];
        post?: never;
        /** @description ViewSet for managing players. */
        delete: operations["players_destroy"];
        options?: never;
        head?: never;
        /** @description Partially update player info */
        patch: operations["players_partial_update"];
        trace?: never;
    };
    "/api/world-states/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List world states */
        get: operations["world_states_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/world-states/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get world state details */
        get: operations["world_states_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Serializer for creating new characters. */
        CharacterCreate: {
            game: number;
            owner: number;
            /** @description Reference to character definition in content service */
            character_type: string;
            name: string;
            is_hero?: boolean;
            /**
             * Format: int64
             * @description Current Q coordinate
             */
            position_q: number;
            /**
             * Format: int64
             * @description Current R coordinate
             */
            position_r: number;
            /** Format: int64 */
            max_health?: number;
            /** Format: int64 */
            max_stamina?: number;
            /** Format: int64 */
            max_movement_points?: number;
            /** Format: int64 */
            inventory_capacity?: number;
            /** @description Character attributes: {strength, agility, intelligence, etc.} */
            attributes?: unknown;
        };
        /** @description Detailed serializer for character detail views. */
        CharacterDetail: {
            readonly id: number;
            game: number;
            owner: number;
            readonly owner_name: string;
            /** @description Reference to character definition in content service */
            character_type: string;
            name: string;
            is_hero?: boolean;
            /** Format: int64 */
            health?: number;
            /** Format: int64 */
            max_health?: number;
            /** Format: int64 */
            stamina?: number;
            /** Format: int64 */
            max_stamina?: number;
            /** Format: int64 */
            experience?: number;
            /** Format: int64 */
            level?: number;
            /**
             * Format: int64
             * @description Current Q coordinate
             */
            position_q: number;
            /**
             * Format: int64
             * @description Current R coordinate
             */
            position_r: number;
            status?: components["schemas"]["StatusBafEnum"];
            /** @description Queue of hex coordinates for movement: [{q, r}, ...] */
            movement_path?: unknown;
            /** Format: int64 */
            movement_points?: number;
            /** Format: int64 */
            max_movement_points?: number;
            /** @description Character inventory: [{item_id, quantity, equipped}, ...] */
            inventory?: unknown;
            /** Format: int64 */
            inventory_capacity?: number;
            readonly inventory_count: string;
            /** @description Current orders: {order_type, target, parameters} */
            current_orders?: unknown;
            in_combat?: boolean;
            combat_id?: string;
            /** @description Character attributes: {strength, agility, intelligence, etc.} */
            attributes?: unknown;
            /** @description Learned skills/abilities: [{skill_id, level, cooldown}, ...] */
            skills?: unknown;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: date-time */
            readonly died_at: string | null;
        };
        /** @description Lightweight serializer for character list views. */
        CharacterList: {
            readonly id: number;
            game: number;
            owner: number;
            readonly owner_name: string;
            /** @description Reference to character definition in content service */
            character_type: string;
            name: string;
            is_hero?: boolean;
            /** Format: int64 */
            health?: number;
            /** Format: int64 */
            max_health?: number;
            /**
             * Format: int64
             * @description Current Q coordinate
             */
            position_q: number;
            /**
             * Format: int64
             * @description Current R coordinate
             */
            position_r: number;
            status?: components["schemas"]["StatusBafEnum"];
            /** Format: int64 */
            level?: number;
            in_combat?: boolean;
        };
        /** @description Serializer for updating character state. */
        CharacterUpdate: {
            /** Format: int64 */
            health?: number;
            /** Format: int64 */
            stamina?: number;
            /** Format: int64 */
            experience?: number;
            /** Format: int64 */
            level?: number;
            /**
             * Format: int64
             * @description Current Q coordinate
             */
            position_q: number;
            /**
             * Format: int64
             * @description Current R coordinate
             */
            position_r: number;
            status?: components["schemas"]["StatusBafEnum"];
            /** @description Queue of hex coordinates for movement: [{q, r}, ...] */
            movement_path?: unknown;
            /** Format: int64 */
            movement_points?: number;
            /** @description Character inventory: [{item_id, quantity, equipped}, ...] */
            inventory?: unknown;
            /** @description Current orders: {order_type, target, parameters} */
            current_orders?: unknown;
            in_combat?: boolean;
            combat_id?: string;
            /** @description Character attributes: {strength, agility, intelligence, etc.} */
            attributes?: unknown;
            /** @description Learned skills/abilities: [{skill_id, level, cooldown}, ...] */
            skills?: unknown;
        };
        /** @description Serializer for creating new games. */
        GameCreate: {
            name: string;
            /** Format: int64 */
            max_players?: number;
            /** Format: int64 */
            tick_duration_minutes?: number;
            map_name: string;
            /** Format: int64 */
            map_width?: number;
            /** Format: int64 */
            map_height?: number;
            settings?: unknown;
        };
        /** @description Detailed serializer for game detail views. */
        GameDetail: {
            readonly id: number;
            name: string;
            status?: components["schemas"]["Status129Enum"];
            /** Format: int64 */
            max_players?: number;
            readonly player_count: string;
            readonly current_tick: number;
            /** Format: int64 */
            tick_duration_minutes?: number;
            map_name: string;
            /** Format: int64 */
            map_width?: number;
            /** Format: int64 */
            map_height?: number;
            settings?: unknown;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            next_tick_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Lightweight serializer for game list views. */
        GameList: {
            readonly id: number;
            name: string;
            status?: components["schemas"]["Status129Enum"];
            /** Format: int64 */
            max_players?: number;
            readonly player_count: string;
            readonly current_tick: number;
            /** Format: int64 */
            tick_duration_minutes?: number;
            map_name: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            next_tick_at?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description Serializer for hex tiles. */
        HexTile: {
            readonly id: number;
            game: number;
            /**
             * Format: int64
             * @description Axial coordinate Q
             */
            q: number;
            /**
             * Format: int64
             * @description Axial coordinate R
             */
            r: number;
            terrain_type?: components["schemas"]["TerrainTypeEnum"];
            /** Format: int64 */
            elevation?: number;
            is_passable?: boolean;
            /** @description Visibility state per player: {player_id: {visible, last_seen_tick}} */
            visibility?: unknown;
            /** @description Structure data: {type, owner_id, health, level, etc.} */
            structure?: unknown;
            /** @description Active effects on tile: [{effect_type, duration, parameters}] */
            effects?: unknown;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Lightweight serializer for hex tile list views. */
        HexTileList: {
            readonly id: number;
            /**
             * Format: int64
             * @description Axial coordinate Q
             */
            q: number;
            /**
             * Format: int64
             * @description Axial coordinate R
             */
            r: number;
            terrain_type?: components["schemas"]["TerrainTypeEnum"];
            /** Format: int64 */
            elevation?: number;
            is_passable?: boolean;
            readonly has_structure: string;
        };
        /** @description Serializer for interactable objects. */
        Interactable: {
            readonly id: number;
            game: number;
            interactable_type: components["schemas"]["InteractableTypeEnum"];
            /** @description Reference to interactable definition */
            interactable_id: string;
            name: string;
            /**
             * Format: int64
             * @description Q coordinate
             */
            position_q: number;
            /**
             * Format: int64
             * @description R coordinate
             */
            position_r: number;
            state?: components["schemas"]["StateEnum"];
            is_active?: boolean;
            /** @description Items required to interact: [item_id, ...] */
            required_items?: unknown;
            /** Format: int64 */
            required_level?: number;
            /** @description Possible loot drops: [{item_id, quantity, probability}, ...] */
            loot_table?: unknown;
            /**
             * Format: int64
             * @description 0 = unlimited
             */
            max_uses?: number;
            readonly current_uses: number;
            /** Format: int64 */
            cooldown_ticks?: number;
            readonly last_used_tick: number | null;
            /** @description Type-specific data: {dialogue, destination, rewards, etc.} */
            data?: unknown;
            /** @description History of interactions: [{character_id, tick, result}, ...] */
            interactions?: unknown;
            readonly can_use: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer for creating interactable objects. */
        InteractableCreate: {
            game: number;
            interactable_type: components["schemas"]["InteractableTypeEnum"];
            /** @description Reference to interactable definition */
            interactable_id: string;
            name: string;
            /**
             * Format: int64
             * @description Q coordinate
             */
            position_q: number;
            /**
             * Format: int64
             * @description R coordinate
             */
            position_r: number;
            state?: components["schemas"]["StateEnum"];
            /** @description Items required to interact: [item_id, ...] */
            required_items?: unknown;
            /** Format: int64 */
            required_level?: number;
            /** @description Possible loot drops: [{item_id, quantity, probability}, ...] */
            loot_table?: unknown;
            /**
             * Format: int64
             * @description 0 = unlimited
             */
            max_uses?: number;
            /** Format: int64 */
            cooldown_ticks?: number;
            /** @description Type-specific data: {dialogue, destination, rewards, etc.} */
            data?: unknown;
        };
        /** @description Lightweight serializer for interactable list views. */
        InteractableList: {
            readonly id: number;
            interactable_type: components["schemas"]["InteractableTypeEnum"];
            name: string;
            /**
             * Format: int64
             * @description Q coordinate
             */
            position_q: number;
            /**
             * Format: int64
             * @description R coordinate
             */
            position_r: number;
            state?: components["schemas"]["StateEnum"];
            is_active?: boolean;
        };
        /**
         * @description * `chest` - Chest
         *     * `door` - Door
         *     * `npc` - NPC
         *     * `portal` - Portal
         *     * `shrine` - Shrine
         *     * `trap` - Trap
         *     * `resource_node` - Resource Node
         *     * `puzzle` - Puzzle
         * @enum {string}
         */
        InteractableTypeEnum: "chest" | "door" | "npc" | "portal" | "shrine" | "trap" | "resource_node" | "puzzle";
        /** @description Serializer for map items (loot). */
        MapItem: {
            readonly id: number;
            game: number;
            /** @description Reference to item definition in content service */
            item_type: string;
            /** @description Unique item instance ID */
            item_id: string;
            /**
             * Format: int64
             * @description Q coordinate
             */
            position_q: number;
            /**
             * Format: int64
             * @description R coordinate
             */
            position_r: number;
            /** Format: int64 */
            quantity?: number;
            rarity?: components["schemas"]["RarityEnum"];
            is_available?: boolean;
            is_locked?: boolean;
            /** Format: int64 */
            spawned_at_tick: number;
            /** Format: int64 */
            despawn_at_tick?: number | null;
            /** @description What spawned this: chest, mob_drop, world_spawn, etc. */
            source_type?: string;
            source_id?: string;
            /** @description Item-specific data: {durability, enchantments, etc.} */
            item_data?: unknown;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly collected_at: string | null;
            readonly collected_by: number | null;
            readonly collected_by_name: string | null;
        };
        /** @description Serializer for spawning map items. */
        MapItemCreate: {
            game: number;
            /** @description Reference to item definition in content service */
            item_type: string;
            /** @description Unique item instance ID */
            item_id: string;
            /**
             * Format: int64
             * @description Q coordinate
             */
            position_q: number;
            /**
             * Format: int64
             * @description R coordinate
             */
            position_r: number;
            /** Format: int64 */
            quantity?: number;
            rarity?: components["schemas"]["RarityEnum"];
            is_locked?: boolean;
            /** Format: int64 */
            spawned_at_tick: number;
            /** Format: int64 */
            despawn_at_tick?: number | null;
            /** @description What spawned this: chest, mob_drop, world_spawn, etc. */
            source_type?: string;
            source_id?: string;
            /** @description Item-specific data: {durability, enchantments, etc.} */
            item_data?: unknown;
        };
        /** @description Lightweight serializer for map item list views. */
        MapItemList: {
            readonly id: number;
            /** @description Reference to item definition in content service */
            item_type: string;
            /**
             * Format: int64
             * @description Q coordinate
             */
            position_q: number;
            /**
             * Format: int64
             * @description R coordinate
             */
            position_r: number;
            /** Format: int64 */
            quantity?: number;
            rarity?: components["schemas"]["RarityEnum"];
            is_available?: boolean;
            is_locked?: boolean;
        };
        /** @description Serializer for updating character state. */
        PatchedCharacterUpdate: {
            /** Format: int64 */
            health?: number;
            /** Format: int64 */
            stamina?: number;
            /** Format: int64 */
            experience?: number;
            /** Format: int64 */
            level?: number;
            /**
             * Format: int64
             * @description Current Q coordinate
             */
            position_q?: number;
            /**
             * Format: int64
             * @description Current R coordinate
             */
            position_r?: number;
            status?: components["schemas"]["StatusBafEnum"];
            /** @description Queue of hex coordinates for movement: [{q, r}, ...] */
            movement_path?: unknown;
            /** Format: int64 */
            movement_points?: number;
            /** @description Character inventory: [{item_id, quantity, equipped}, ...] */
            inventory?: unknown;
            /** @description Current orders: {order_type, target, parameters} */
            current_orders?: unknown;
            in_combat?: boolean;
            combat_id?: string;
            /** @description Character attributes: {strength, agility, intelligence, etc.} */
            attributes?: unknown;
            /** @description Learned skills/abilities: [{skill_id, level, cooldown}, ...] */
            skills?: unknown;
        };
        /** @description Detailed serializer for game detail views. */
        PatchedGameDetail: {
            readonly id?: number;
            name?: string;
            status?: components["schemas"]["Status129Enum"];
            /** Format: int64 */
            max_players?: number;
            readonly player_count?: string;
            readonly current_tick?: number;
            /** Format: int64 */
            tick_duration_minutes?: number;
            map_name?: string;
            /** Format: int64 */
            map_width?: number;
            /** Format: int64 */
            map_height?: number;
            settings?: unknown;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            next_tick_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /** @description Serializer for hex tiles. */
        PatchedHexTile: {
            readonly id?: number;
            game?: number;
            /**
             * Format: int64
             * @description Axial coordinate Q
             */
            q?: number;
            /**
             * Format: int64
             * @description Axial coordinate R
             */
            r?: number;
            terrain_type?: components["schemas"]["TerrainTypeEnum"];
            /** Format: int64 */
            elevation?: number;
            is_passable?: boolean;
            /** @description Visibility state per player: {player_id: {visible, last_seen_tick}} */
            visibility?: unknown;
            /** @description Structure data: {type, owner_id, health, level, etc.} */
            structure?: unknown;
            /** @description Active effects on tile: [{effect_type, duration, parameters}] */
            effects?: unknown;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /** @description Serializer for interactable objects. */
        PatchedInteractable: {
            readonly id?: number;
            game?: number;
            interactable_type?: components["schemas"]["InteractableTypeEnum"];
            /** @description Reference to interactable definition */
            interactable_id?: string;
            name?: string;
            /**
             * Format: int64
             * @description Q coordinate
             */
            position_q?: number;
            /**
             * Format: int64
             * @description R coordinate
             */
            position_r?: number;
            state?: components["schemas"]["StateEnum"];
            is_active?: boolean;
            /** @description Items required to interact: [item_id, ...] */
            required_items?: unknown;
            /** Format: int64 */
            required_level?: number;
            /** @description Possible loot drops: [{item_id, quantity, probability}, ...] */
            loot_table?: unknown;
            /**
             * Format: int64
             * @description 0 = unlimited
             */
            max_uses?: number;
            readonly current_uses?: number;
            /** Format: int64 */
            cooldown_ticks?: number;
            readonly last_used_tick?: number | null;
            /** @description Type-specific data: {dialogue, destination, rewards, etc.} */
            data?: unknown;
            /** @description History of interactions: [{character_id, tick, result}, ...] */
            interactions?: unknown;
            readonly can_use?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /** @description Serializer for map items (loot). */
        PatchedMapItem: {
            readonly id?: number;
            game?: number;
            /** @description Reference to item definition in content service */
            item_type?: string;
            /** @description Unique item instance ID */
            item_id?: string;
            /**
             * Format: int64
             * @description Q coordinate
             */
            position_q?: number;
            /**
             * Format: int64
             * @description R coordinate
             */
            position_r?: number;
            /** Format: int64 */
            quantity?: number;
            rarity?: components["schemas"]["RarityEnum"];
            is_available?: boolean;
            is_locked?: boolean;
            /** Format: int64 */
            spawned_at_tick?: number;
            /** Format: int64 */
            despawn_at_tick?: number | null;
            /** @description What spawned this: chest, mob_drop, world_spawn, etc. */
            source_type?: string;
            source_id?: string;
            /** @description Item-specific data: {durability, enchantments, etc.} */
            item_data?: unknown;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly collected_at?: string | null;
            readonly collected_by?: number | null;
            readonly collected_by_name?: string | null;
        };
        /** @description Detailed serializer for player detail views. */
        PatchedPlayerDetail: {
            readonly id?: number;
            game?: number;
            readonly user?: components["schemas"]["User"];
            player_name?: string;
            color?: string;
            avatar?: string;
            is_active?: boolean;
            is_ai?: boolean;
            /** Format: date-time */
            defeated_at?: string | null;
            /** Format: int64 */
            score?: number;
            /** @description Current resources: {resource_type: amount} */
            resources?: unknown;
            /** @description List of researched tech IDs */
            researched_technologies?: unknown;
            /** @description Current research progress */
            current_research?: unknown;
            /** @description Diplomatic relations: {player_id: {status, since_tick}} */
            diplomacy?: unknown;
            readonly character_count?: string;
            /** Format: date-time */
            readonly joined_at?: string;
            /** Format: date-time */
            readonly last_active_at?: string;
        };
        /** @description Serializer for joining a game as a player. */
        PlayerCreate: {
            game: number;
            player_name: string;
            color?: string;
            avatar?: string;
        };
        /** @description Detailed serializer for player detail views. */
        PlayerDetail: {
            readonly id: number;
            game: number;
            readonly user: components["schemas"]["User"];
            player_name: string;
            color?: string;
            avatar?: string;
            is_active?: boolean;
            is_ai?: boolean;
            /** Format: date-time */
            defeated_at?: string | null;
            /** Format: int64 */
            score?: number;
            /** @description Current resources: {resource_type: amount} */
            resources?: unknown;
            /** @description List of researched tech IDs */
            researched_technologies?: unknown;
            /** @description Current research progress */
            current_research?: unknown;
            /** @description Diplomatic relations: {player_id: {status, since_tick}} */
            diplomacy?: unknown;
            readonly character_count: string;
            /** Format: date-time */
            readonly joined_at: string;
            /** Format: date-time */
            readonly last_active_at: string;
        };
        /** @description Lightweight serializer for player list views. */
        PlayerList: {
            readonly id: number;
            game: number;
            readonly user: components["schemas"]["User"];
            player_name: string;
            color?: string;
            avatar?: string;
            is_active?: boolean;
            is_ai?: boolean;
            /** Format: int64 */
            score?: number;
            readonly character_count: string;
            /** Format: date-time */
            readonly joined_at: string;
            /** Format: date-time */
            readonly last_active_at: string;
        };
        /**
         * @description * `common` - Common
         *     * `uncommon` - Uncommon
         *     * `rare` - Rare
         *     * `epic` - Epic
         *     * `legendary` - Legendary
         * @enum {string}
         */
        RarityEnum: "common" | "uncommon" | "rare" | "epic" | "legendary";
        /**
         * @description * `active` - Active
         *     * `used` - Used
         *     * `destroyed` - Destroyed
         *     * `locked` - Locked
         *     * `unlocked` - Unlocked
         * @enum {string}
         */
        StateEnum: "active" | "used" | "destroyed" | "locked" | "unlocked";
        /**
         * @description * `waiting` - Waiting for Players
         *     * `active` - Active
         *     * `paused` - Paused
         *     * `finished` - Finished
         * @enum {string}
         */
        Status129Enum: "waiting" | "active" | "paused" | "finished";
        /**
         * @description * `idle` - Idle
         *     * `moving` - Moving
         *     * `looting` - Looting
         *     * `interacting` - Interacting
         *     * `in_combat` - In Combat
         *     * `dead` - Dead
         * @enum {string}
         */
        StatusBafEnum: "idle" | "moving" | "looting" | "interacting" | "in_combat" | "dead";
        /**
         * @description * `plains` - Plains
         *     * `forest` - Forest
         *     * `mountain` - Mountain
         *     * `water` - Water
         *     * `desert` - Desert
         *     * `swamp` - Swamp
         *     * `snow` - Snow
         *     * `urban` - Urban
         * @enum {string}
         */
        TerrainTypeEnum: "plains" | "forest" | "mountain" | "water" | "desert" | "swamp" | "snow" | "urban";
        /** @description Serializer for User model. */
        User: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /**
             * Email address
             * Format: email
             */
            email?: string;
            first_name?: string;
            last_name?: string;
        };
        /** @description Serializer for WorldState snapshots. */
        WorldState: {
            readonly id: number;
            game: number;
            /** Format: int64 */
            tick: number;
            /** @description Complete denormalized game state */
            state_snapshot?: unknown;
            readonly is_current: boolean;
            /** Format: int64 */
            active_players?: number;
            /** Format: int64 */
            total_characters?: number;
            /** Format: int64 */
            commands_processed?: number;
            /** @description SHA256 hash of state_snapshot */
            readonly state_hash: string;
            /** @description List of events that occurred this tick */
            events?: unknown;
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description Lightweight serializer for world state list views. */
        WorldStateList: {
            readonly id: number;
            game: number;
            /** Format: int64 */
            tick: number;
            is_current?: boolean;
            /** Format: int64 */
            active_players?: number;
            /** Format: int64 */
            total_characters?: number;
            /** Format: int64 */
            commands_processed?: number;
            /** Format: date-time */
            readonly created_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    characters_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterList"][];
                };
            };
        };
    };
    characters_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["CharacterCreate"];
                "multipart/form-data": components["schemas"]["CharacterCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterCreate"];
                };
            };
        };
    };
    characters_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Character. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
        };
    };
    characters_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Character. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["CharacterUpdate"];
                "multipart/form-data": components["schemas"]["CharacterUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterUpdate"];
                };
            };
        };
    };
    characters_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Character. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    characters_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Character. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCharacterUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCharacterUpdate"];
                "multipart/form-data": components["schemas"]["PatchedCharacterUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterUpdate"];
                };
            };
        };
    };
    characters_loot_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Character. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    item_id: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
        };
    };
    characters_move_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Character. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    q: number;
                    r: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetail"];
                };
            };
        };
    };
    games_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameList"][];
                };
            };
        };
    };
    games_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["GameCreate"];
                "multipart/form-data": components["schemas"]["GameCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameCreate"];
                };
            };
        };
    };
    games_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Game. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
        };
    };
    games_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Game. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["GameDetail"];
                "multipart/form-data": components["schemas"]["GameDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
        };
    };
    games_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Game. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    games_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Game. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedGameDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedGameDetail"];
                "multipart/form-data": components["schemas"]["PatchedGameDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
        };
    };
    games_current_state_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Game. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldState"];
                };
            };
        };
    };
    games_start_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Game. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["GameDetail"];
                "multipart/form-data": components["schemas"]["GameDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
        };
    };
    hex_tiles_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HexTileList"][];
                };
            };
        };
    };
    hex_tiles_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HexTile"];
                "application/x-www-form-urlencoded": components["schemas"]["HexTile"];
                "multipart/form-data": components["schemas"]["HexTile"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HexTile"];
                };
            };
        };
    };
    hex_tiles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Hex Tile. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HexTile"];
                };
            };
        };
    };
    hex_tiles_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Hex Tile. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HexTile"];
                "application/x-www-form-urlencoded": components["schemas"]["HexTile"];
                "multipart/form-data": components["schemas"]["HexTile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HexTile"];
                };
            };
        };
    };
    hex_tiles_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Hex Tile. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    hex_tiles_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Hex Tile. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedHexTile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedHexTile"];
                "multipart/form-data": components["schemas"]["PatchedHexTile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HexTile"];
                };
            };
        };
    };
    hex_tiles_nearby_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HexTileList"][];
                };
            };
        };
    };
    interactables_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractableList"][];
                };
            };
        };
    };
    interactables_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InteractableCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["InteractableCreate"];
                "multipart/form-data": components["schemas"]["InteractableCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InteractableCreate"];
                };
            };
        };
    };
    interactables_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Interactable. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Interactable"];
                };
            };
        };
    };
    interactables_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Interactable. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Interactable"];
                "application/x-www-form-urlencoded": components["schemas"]["Interactable"];
                "multipart/form-data": components["schemas"]["Interactable"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Interactable"];
                };
            };
        };
    };
    interactables_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Interactable. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    interactables_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Interactable. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedInteractable"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedInteractable"];
                "multipart/form-data": components["schemas"]["PatchedInteractable"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Interactable"];
                };
            };
        };
    };
    interactables_interact_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Interactable. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    character_id: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Interactable"];
                };
            };
        };
    };
    map_items_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapItemList"][];
                };
            };
        };
    };
    map_items_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapItemCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["MapItemCreate"];
                "multipart/form-data": components["schemas"]["MapItemCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapItemCreate"];
                };
            };
        };
    };
    map_items_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Map Item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapItem"];
                };
            };
        };
    };
    map_items_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Map Item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapItem"];
                "application/x-www-form-urlencoded": components["schemas"]["MapItem"];
                "multipart/form-data": components["schemas"]["MapItem"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapItem"];
                };
            };
        };
    };
    map_items_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Map Item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    map_items_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Map Item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMapItem"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMapItem"];
                "multipart/form-data": components["schemas"]["PatchedMapItem"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapItem"];
                };
            };
        };
    };
    players_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerList"][];
                };
            };
        };
    };
    players_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["PlayerCreate"];
                "multipart/form-data": components["schemas"]["PlayerCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerCreate"];
                };
            };
        };
    };
    players_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Player. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerDetail"];
                };
            };
        };
    };
    players_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Player. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["PlayerDetail"];
                "multipart/form-data": components["schemas"]["PlayerDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerDetail"];
                };
            };
        };
    };
    players_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Player. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    players_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this Player. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPlayerDetail"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPlayerDetail"];
                "multipart/form-data": components["schemas"]["PatchedPlayerDetail"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerDetail"];
                };
            };
        };
    };
    world_states_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldStateList"][];
                };
            };
        };
    };
    world_states_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this World State. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldState"];
                };
            };
        };
    };
}
